import './globals.css'
import Nav from '../components/Nav'
import Footer from '@/components/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-gray-100 text-gray-800 font-nuni max-w-5xl'>
        <Nav />
        {children}
        <Footer/>

      </body>
    </html>
  )
}
