import './globals.css'
import Nav from '../components/Nav'
import Footer from '@/components/Footer'

export const metadata = {
  title:'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-gray-100 flex flex-col items-center'>
        <main className=' w-full font-nuni min-h-screen max-w-6xl'>
        <Nav />
        {children} 
        </main>
        <Footer/>
      </body>
    </html>
  )
}
